---
title: "D_M100"
output: pdf_document
date: "2024-05-25"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning=FALSE, message=FALSE}
library(MASS)
library(car)
library(pscl)
```

```{r, warning=FALSE, message=FALSE}
source("/Final/Functions.R")
source("/Final/D_Functions.R")
```

```{r}
path <- "/Final/M100/D/"

for (i in 1:4) {
  filename <- paste0(path, "D_M100_", i, ".csv")
  file_data <- read.csv(filename)
  assign(paste0("df", i), file_data)
}
```

```{r}
truth = read.csv("/Gridded_regions/Internship/KM/truth_km.csv")
truth = truth[order(truth$GM_NAAM), ]
point_data = read.csv("/Gridded_regions/Internship/point_data.csv")
```

```{r}
library(dplyr)
truth_numpoints <- point_data %>%
  group_by(GM_NAAM) %>%
  summarise(Count = sum(AANTPERS_v), .groups = 'drop')
```

## Analysis


```{r}
d_m100 = rbind(df1,df2,df3,df4)
d_m100$AANTPERS_v_sum[is.na(d_m100$AANTPERS_v_sum)] = 0
```

```{r}
sum(d_m100$AANTPERS_v_sum == 0)
1001744/nrow(d_m100)
```

```{r}
summary(d_m100$UrbanArea)
summary(d_m100$RecArea)
summary(d_m100$AgriArea)
summary(d_m100$AANTPERS_v_sum)
var(d_m100$AANTPERS_v_sum)
```

```{r}
dataframes = list(d_m100, df1, df2, df3, df4)
columns_to_scale = c("UrbanArea", "RecArea", "AgriArea", "WaterArea")

for (i in 1:length(dataframes)) {
  df = dataframes[[i]]
  
  for (col in columns_to_scale) {
    df[[col]] = scale(df[[col]])
  }
  
  dataframes[[i]] = df
}

d_m100 = dataframes[[1]]
df1 = dataframes[[2]]
df2 = dataframes[[3]]
df3 = dataframes[[4]]
df4 = dataframes[[5]]

```

## Poisson Regression

```{r}
pois = glm(AANTPERS_v_sum ~ UrbanArea + RecArea + factor(GM_NAAM), family = poisson(), data = d_m100)
pois$deviance
pois$deviance / pois$df.residua
```


## Zero-inflated Negative Binomial Regression

```{r}
set.seed(123)
trainIndex <- createDataPartition(d_m100$AANTPERS_v_sum, p = .5, 
                                  list = FALSE, 
                                  times = 1)

trainData <- d_m100[ trainIndex,]
testData  <- d_m100[-trainIndex,]
```

```{r}
zinb_model = zeroinfl(AANTPERS_v_sum ~ 
                        UrbanArea + 
                        RecArea +
                        AgriArea +
                        factor(GM_NAAM), 
                      data = trainData, dist = "negbin")
```

## On the test data


```{r}
zi_probs <- predict(zinb_model, newdata = testData, type = "zero")
count_preds = predict(zinb_model, testData, type = "count")
testData$NumPoints = ifelse(is.na(testData$Total_Length_mean), 0, (1 - zi_probs) * count_preds)
```

```{r}
mse_result = calculate_mse_d(testData, truth)
mse_point = calculate_metrics_d(point_data, testData, truth_numpoints, truth)
```

## On the dataframes


```{r}
dataframes = list(df1, df2, df3, df4)

for (i in 1:length(dataframes)) {
  df = dataframes[[i]]
  
  zi_probs = predict(zinb_model, df, type = "zero")
  
  count_preds = predict(zinb_model, df, type = "count")
  
  df$NumPoints = ifelse(is.na(df$Total_Length_mean), 0, (1 - zi_probs) * count_preds)
  
  dataframes[[i]] = df
}

df1 = dataframes[[1]]
df2 = dataframes[[2]]
df3 = dataframes[[3]]
df4 = dataframes[[4]]
```

```{r}
for (i in 1:4) {
  df_name = paste0("df", i)
  truth_name = paste0("truth")

  df_dataset = get(df_name)
  truth_dataset = get(truth_name)
  
  mse_result = calculate_mse_d(df_dataset, truth_dataset)

  km_name = paste0("m100_", i)
  assign(km_name, mse_result)
}
```

```{r}
for (i in 1:4){
  df_name = paste0("df", i)
  df_dataset = get(df_name)
  
  mse_point = calculate_metrics_d(point_data, df_dataset, truth_numpoints, truth)
  
  name = paste0("m100_points_", i)
  assign(name, mse_point)
}
```

```{r}
for (i in 1:4) {
  name = paste0("m100_", i)
  points_name = paste0("m100_points_", i)
  
  assign(name, transform(get(name), position = paste0('f', i), size = 'm100', method = 'D'))

  assign(points_name, transform(get(points_name), position = paste0('f', i), size = 'm100', method = 'D'))
}
```

```{r}
m100_mse = rbind(m100_1,m100_2, m100_3, m100_4)
m100_mse$rmse = sqrt(m100_mse$mse)

m100_points = rbind(m100_points_1, m100_points_2, m100_points_3, m100_points_4)
m100_points$rmse = sqrt(m100_points$mse)
```

```{r}
anova_result = aov(rmse ~ position, data = m100_mse)
summary(anova_result)
```

```{r}
anova_result = aov(rmse ~ position, data = m100_points)
summary(anova_result)
```


```{r}
#library(openxlsx)
#write.xlsx(m100_mse, file = "/Final/M100/D/D_M100.xlsx")
#write.xlsx(m100_points, file = "/Final/M100/D/D_M100_points.xlsx")
```


## For the results

```{r}
for (i in 1:4) {
  df_name = paste0("df", i)

  df_dataset = get(df_name)
  
  distance_result = calculate_distance_d(df_dataset)

  name = paste0("m100_dist_result_", i)
  assign(name, distance_result)
}
```

```{r}
for (i in 1:4){
  df_name = paste0("df", i)
  df_dataset = get(df_name)
  
  points_result = calculate_points_d(point_data, df_dataset)
  
  name = paste0("m100_points_result_", i)
  assign(name, points_result)
}
```

```{r}
for (i in 1:4) {
  name = paste0("m100_dist_result_", i)
  points_name = paste0("m100_points_result_", i)
  
  assign(name, transform(get(name), position = paste0('f', i), size = 'm100', method = 'D'))

  assign(points_name, transform(get(points_name), position = paste0('f', i), size = 'm100', method = 'D'))
}
```

```{r}
m100_dist_result = rbind(m100_dist_result_1, m100_dist_result_2, m100_dist_result_3, m100_dist_result_4)
m100_points_result = rbind(m100_points_result_1, m100_points_result_2, m100_points_result_3, m100_points_result_4)
```


```{r}
#library(openxlsx)
#write.xlsx(m100_dist_result, file = "/Final/M100/D/D_M100_dist_result.xlsx")
#write.xlsx(m100_points_result, file = "/Final/M100/D/D_M100_points_result.xlsx")
```



